FROM apache/spark:3.2.0-python3

USER root

# Install wget
RUN apt-get update && apt-get install -y wget

# Download Kafka connector for Spark
RUN wget https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar -P /opt/spark/jars/

# Copy your application JAR
COPY out/artifacts/MovieDataProcessor_jar/MovieDataProcessor.jar /opt/spark/work-dir/app.jar

# Set the working directory
WORKDIR /opt/spark/work-dir

# Run the Spark job
CMD ["spark-submit", "--class", "SparkKafkaCassandra", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0", "app.jar"]
