FROM bitnami/spark:3.2.0

USER root

# Install wget
RUN install_packages wget

# Download Kafka connector for Spark
RUN wget https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.0/spark-sql-kafka-0-10_2.12-3.2.0.jar -P /opt/bitnami/spark/jars/

# Copy your updated application JAR
COPY target/scala-2.12/your-spark-app.jar /opt/bitnami/spark/work-dir/app.jar

# Set the working directory
WORKDIR /opt/bitnami/spark/work-dir

# Run the Spark job
CMD ["/opt/bitnami/spark/bin/spark-submit", "--class", "SparkKafkaCassandra", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0,com.datastax.spark:spark-cassandra-connector_2.12:3.1.0", "app.jar"]
