FROM openjdk:11-jre-slim as builder
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
COPY src/main/resources/data.sql /app/data.sql

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
